Repository MicrosoftDocs/WindowsCommunityToolkitDocs, pull requests merged in 2020-06, with the labels that each got.

#336 Add note about running WebViewCompatible as admin
  docs/controls/wpf-winforms/WebViewCompatible.md
Labels: triaged :+1:

#322 Add spacing properties to docs
  docs/controls/StaggeredPanel.md
  docs/controls/WrapPanel.md
Labels: triaged :+1:

#319 Fixed dead links
  docs/extensions/ViewExtensions.md
Labels: triaged :+1:

#306 Update ObjectStorage with new constructor parameter
  docs/helpers/ObjectSerializer.md
  docs/helpers/ObjectStorage.md
  docs/toc.md
Labels: assigned-to-author :rocket:

#308 Add documentation for the new `ClipToBounds` property
  docs/extensions/UIElementExtensions.md
  docs/toc.md
Labels: Ready for Review ✋

#302 Guard APIs docs
  docs/developer-tools/Guard.md
  docs/toc.md
Labels: Ready for Review ✋

#343 Fix broken links
  docs/helpers/Colors.md
  docs/helpers/StorageFiles.md
  docs/helpers/Streams.md
  docs/helpers/ThemeListener.md
  docs/helpers/WeakEventListener.md
  docs/platform-specific/PlatformSpecificDifferencesGenerator.md
  docs/services/Linkedin.md
  docs/services/MicrosoftTranslator.md
Labels: assigned-to-author :rocket:
