Repository MicrosoftDocs/WindowsCommunityToolkitDocs, pull requests merged in 2021-09, with the labels that each got.

#559 ListDetailsView Two-pane view documentation update
  docs/controls/MasterDetailsView.md
  dotnet/xml/FrameworksIndex/win-comm-toolkit-dotnet-7.0.xml
  dotnet/xml/Microsoft.Toolkit.Uwp.UI.Controls/ListDetailsView.xml
Labels: Ready for Review ✋

#556 Add markdown documentation for new KeyDownTriggerBehavior
  docs/behaviors/KeyDownTriggerBehavior.md
  docs/toc.md
Labels: Ready for Review ✋

#551 Addings docs for new ControlSizeTrigger
  docs/helpers/Triggers.md
Labels: Ready for Review ✋

#537 Add MetadataControl documentation
  docs/controls/MetadataControl.md
  docs/toc.md
Labels: Ready for Review ✋

#558 Documentation for RichSuggestBox control
  docs/controls/RichSuggestBox.md
  docs/resources/images/Controls/RichSuggestBox.gif
  docs/toc.md
Labels: Ready for Review ✋

#571 Outlined instead of outline
  docs/mvvm/PuttingThingsTogether.md
Labels: bug :bug:, doc-bug :beetle:

#572 Add missing UnitTests.Shared subdirectory to unit tests URL
  docs/developer-tools/Guard.md
Labels: bug :bug:, doc-bug :beetle:

#573 Update markdown file to refer to Diagnostics Nuget Pkg
  docs/diagnostics/Introduction.md
Labels: bug :bug:, doc-bug :beetle:

#579 Add link to MVVM Sample Application
  docs/mvvm/PuttingThingsTogether.md
Labels: doc-enhancement :sparkles:
